version: '3.8'

services:
  sandbox:
    build: .
    container_name: url-sandbox
    ports:
      - "5000:5000"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
